//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PupaParserComeback.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\master\\Desktop\\1")]
        public string ImportDirectoryPath {
            get {
                return ((string)(this["ImportDirectoryPath"]));
            }
            set {
                this["ImportDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\master\\Documents\\visual studio 2015\\Projects\\PupaParserComeback\\PupaPars" +
            "erComeback.UI\\Images\\")]
        public string PersonalPhotoDirectoryPath {
            get {
                return ((string)(this["PersonalPhotoDirectoryPath"]));
            }
            set {
                this["PersonalPhotoDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\master\\Documents\\Visual Studio 2015\\Projects\\PupaParserComeback\\PupaPars" +
            "erComeback.Data.Firebird\\Db\\FORM2017-2.GDB")]
        public string FirebirdLocalFilePath {
            get {
                return ((string)(this["FirebirdLocalFilePath"]));
            }
            set {
                this["FirebirdLocalFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\master\\Documents\\visual studio 2015\\Projects\\PupaParserComeback\\PupaPars" +
            "erComeback.Data.SQLite\\Db\\Main.db")]
        public string SqliteLocalFilePath {
            get {
                return ((string)(this["SqliteLocalFilePath"]));
            }
            set {
                this["SqliteLocalFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\master\\Documents\\visual studio 2015\\Projects\\PupaParserComeback\\PupaPars" +
            "erComeback.UI\\Templates\\ABPattern.xls")]
        public string ExportTemplateFilePath {
            get {
                return ((string)(this["ExportTemplateFilePath"]));
            }
            set {
                this["ExportTemplateFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\master\\Documents\\visual studio 2015\\Projects\\PupaParserComeback\\PupaPars" +
            "erComeback.UI\\Templates\\ExportTableTemplate.xlsx")]
        public string ExportTableTemplateFilePath {
            get {
                return ((string)(this["ExportTableTemplateFilePath"]));
            }
            set {
                this["ExportTableTemplateFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\master\\Documents\\visual studio 2015\\Projects\\PupaParserComeback\\PupaPars" +
            "erComeback.Export\\ExportedFiles")]
        public string ExportDirectoryPath {
            get {
                return ((string)(this["ExportDirectoryPath"]));
            }
            set {
                this["ExportDirectoryPath"] = value;
            }
        }
    }
}
